# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ack
version:      1.60
version_from: Ack.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Next:                    0.4
    Getopt::Long:                  0
    Term::ANSIColor:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
